// jsonData.js
let json = `[{"id":1,"first_name":"Dorree","last_name":"Abeles","email":"dabeles0@mapquest.com","gender":"Female","salary":8831},
{"id":2,"first_name":"Derry","last_name":"Hablot","email":"dhablot1@angelfire.com","gender":"Male","salary":7289},
{"id":3,"first_name":"Randal","last_name":"Looney","email":"rlooney2@rambler.ru","gender":"Male","salary":5645},
{"id":4,"first_name":"Fredrick","last_name":"Tweed","email":"ftweed3@stanford.edu","gender":"Male","salary":4946},
{"id":5,"first_name":"Geoffrey","last_name":"Kain","email":"gkain4@biblegateway.com","gender":"Genderqueer","salary":2702},
{"id":6,"first_name":"Corabella","last_name":"Joysey","email":"cjoysey5@illinois.edu","gender":"Female","salary":3657},
{"id":7,"first_name":"Kerr","last_name":"Hogbin","email":"khogbin6@stanford.edu","gender":"Male","salary":4117},
{"id":8,"first_name":"Rick","last_name":"Lisett","email":"rlisett7@mtv.com","gender":"Male","salary":5759},
{"id":9,"first_name":"Ashby","last_name":"Bentote","email":"abentote8@bigcartel.com","gender":"Male","salary":4895},
{"id":10,"first_name":"Sibbie","last_name":"Shoebotham","email":"sshoebotham9@unesco.org","gender":"Female","salary":4093},
{"id":11,"first_name":"Oliviero","last_name":"Ygou","email":"oygoua@wufoo.com","gender":"Genderfluid","salary":2814},
{"id":12,"first_name":"Annalee","last_name":"Hulcoop","email":"ahulcoopb@nasa.gov","gender":"Female","salary":8813},
{"id":13,"first_name":"Cris","last_name":"Archley","email":"carchleyc@engadget.com","gender":"Female","salary":3208},
{"id":14,"first_name":"Michele","last_name":"Penney","email":"mpenneyd@cdbaby.com","gender":"Male","salary":5286},
{"id":15,"first_name":"Di","last_name":"Santon","email":"dsantone@angelfire.com","gender":"Female","salary":3496},
{"id":16,"first_name":"Corey","last_name":"Nevinson","email":"cnevinsonf@discovery.com","gender":"Non-binary","salary":2906},
{"id":17,"first_name":"Farly","last_name":"Haslewood","email":"fhaslewoodg@home.pl","gender":"Male","salary":8330},
{"id":18,"first_name":"Ade","last_name":"MacCaghan","email":"amaccaghanh@yandex.ru","gender":"Genderfluid","salary":2751},
{"id":19,"first_name":"Akim","last_name":"Slograve","email":"aslogravei@moonfruit.com","gender":"Male","salary":8044},
{"id":20,"first_name":"Hailee","last_name":"Toffoloni","email":"htoffolonij@howstuffworks.com","gender":"Female","salary":8379}]`;